- Configuration:
    Apply_Config: false
    Authentication:
      pixeldrain_api_key: null
      simpcity_password: '!REDACTED!'
      simpcity_username: null
      socialmediagirls_password: '!REDACTED!'
      socialmediagirls_username: null
      xbunker_password: '!REDACTED!'
      xbunker_username: null
    Files:
      db_file: download_history.sqlite
      input_file: /home/greydon/pv/GitHub/CyberDropDownloader/01-18-2023_urls.txt
      output_folder: /home/greydon/pv/GitHub/CyberDropDownloader/Download
      output_last_forum_post_file: URLs_last_post.txt
    JDownloader:
      jdownloader_device: null
      jdownloader_enable: false
      jdownloader_password: '!REDACTED!'
      jdownloader_username: null
    Runtime:
      attempts: 10
      connection_timeout: 15
      disable_attempt_limit: false
      exclude_audio: false
      exclude_images: false
      exclude_other: false
      exclude_videos: false
      ignore_history: false
      include_id: false
      mark_downloaded: false
      output_last_forum_post: false
      proxy: null
      ratelimit: 50
      required_free_space: 5
      separate_posts: false
      skip_hosts: []
      threads: 0
      throttle: 0.5
