#
#--- dicom2bids
#

#dicom_dir: /home/greydon/Documents/GitHub/seeg2bids-pipeline/data/dicoms
#out_dir: /home/greydon/Documents/GitHub/seeg2bids-pipeline/data/output
#clinical_event_file: /home/greydon/Documents/GitHub/seeg2bids-pipeline/data/clinical_events.tsv
#participants_tsv: /home/greydon/Documents/GitHub/seeg2bids-pipeline/data/participants.tsv
#subject_seega_scene: /home/greydon/Documents/GitHub/seeg2bids-pipeline/data/seega_scenes/sub-P{subject}

dicom_dir: /media/veracrypt6/projects/iEEG/single/dicoms
out_dir: /media/veracrypt6/projects/iEEG/single/out
clinical_event_file: /media/veracrypt6/projects/iEEG/single/clinical_events.tsv
participants_tsv: 
subject_seega_scene: /media/veracrypt6/projects/iEEG/imaging/clinical/deriv/seega_scenes/sub-P{subject}/surg01


#
#--- dicom2bids
#

heuristic: resources/heuristics/clinical_imaging.py
dcm_config: resources/dcm_config.json
anonymize: False
deface: False
sub_group: patient
subject_prefix: P

# Session determination
session_calc:
  peri: 0
  dur_multi_event: -15
  override_peri: True

facemask: resources/facemask.nii.gz
mean_reg2mean: resources/mean_reg2mean.nii.gz

#
#--- segmentation
#

singularity:
    neuroglia: /project/6050199/akhanf/singularity/bids-apps/khanlab_neuroglia-core_latest.sif
# use this URI if not on khanlab compute canada:
#    neuroglia: docker://khanlab/neuroglia-core:latest

subject_t1w: /bids/sub-P{subject}/ses-pre/anat/sub-P{subject}_ses-pre_run-01_T1w.nii.gz

#use this if a particular subject has a custom path
subject_t1w_custom:
    '001': /bids/sub-P{subject}/ses-pre/anat/sub-P{subject}_ses-pre_run-02_T1w.nii.gz
    '007': /bids/sub-P{subject}/ses-pre/anat/sub-P{subject}_ses-pre_run-03_T1w.nii.gz
    '017': /bids/sub-P{subject}/ses-pre/anat/sub-P{subject}_ses-pre_run-02_T1w.nii.gz
    '018': /bids/sub-P{subject}/ses-pre/anat/sub-P{subject}_ses-pre_run-02_T1w.nii.gz
    '020': /seega_old/sub-P{subject}/preop_mri.nii.gz
    '024': /bids/sub-P{subject}/ses-pre/anat/sub-P{subject}_ses-pre_run-02_T1w.nii.gz
    '033': /bids/sub-P{subject}/ses-pre/anat/sub-P{subject}_ses-pre_run-02_T1w.nii.gz
    '042': /seega_old/sub-P{subject}/preop_mri.nii.gz
    #'048': /bids/sub-P{subject}/ses-pre/anat/sub-P{subject}_ses-pre_run-02_T1w.nii.gz
    '052': /bids/sub-P{subject}/ses-pre/anat/sub-P{subject}_ses-pre_run-02_T1w.nii.gz
    '053': /sub-P053/Stokes_David/Data/sub-P053_3D_T1_BRAVO.nii.gz

subject_ct: /bids/sub-P{subject}/ses-post/ct/sub-P{subject}_ses-post_acq-Electrode_run-01_ct.nii.gz

#use this if a particular subject has a custom path
subject_ct_custom:
    '002': /seega_old/sub-P{subject}/ct_to_mri.nii.gz
    '007': /seega_old/sub-P{subject}/ct_to_mri.nii.gz
    '010': /seega_old/sub-P{subject}/ct_to_mri.nii.gz
    '011': /seega_old/sub-P{subject}/ct_to_mri.nii.gz
    '019': /seega_old/sub-P{subject}/ct_to_mri.nii.gz
    '020': /seega_old/sub-P{subject}/ct_to_mri.nii.gz
    '030': /seega_old/sub-P{subject}/ct_to_mri.nii.gz
    '042': /seega_old/sub-P{subject}/ct_to_mri.nii.gz
    '047': /bids/sub-P{subject}/ses-post/ct/sub-P{subject}_ses-post_acq-Electrode_run-03_ct.nii.gz

subject_electrodes: /deriv/seega_coordinates/sub-P{subject}/sub-P{subject}_space-native_SEEGA.fcsv

#use this if a particular subject has custom path
subject_electrodes_custom: []
template: MNI152NLin2009cSym

template_t1w: resources/tpl-{template}/tpl-{template}_res-1_T1w.nii.gz
template_mask: resources/tpl-{template}/tpl-{template}_res-1_desc-brain_mask.nii.gz 

template_atlas_dseg_nii: resources/tpl-{template}/tpl-{template}_res-1_atlas-{atlas}_dseg.nii.gz
template_atlas_dseg_tsv: resources/tpl-{template}/tpl-{template}_atlas-{atlas}_dseg.tsv

template_tissue_probseg: resources/tpl-{template}/tpl-{template}_res-1_label-{tissue}_probseg.nii.gz

tissue_labels:
 - GM
 - WM
 - CSF

atlases:
 - CerebrA

#number of times to dilate  (each time 3x3x3 mode dilation)
n_atlas_dilate: 3
n_init_mask_dilate: 1 

default_k_tissue_classes: 5 #higher than 3 to capture contrast-enhanced regions too

#use this to specify custom values for subjects, e.g. here sub-P001 will have k=4 tissue classes for Atropos initialization
subject_k_tissue_classes:
    P001: 4

#parameters for ants transformation
ants:
    dim: 3
#    random_seed: 42 #requires ants version at least 2.3.1 (includes --random-seed option) - removed this for compatibility with older version of ANTS..  (e.g. that used in neuroglia-core)
    intensity_opts: '-u 1 -w [0.01,0.99] -z 1'
    linear:
        reg_iterations: '1000x500x250x0'
        shrink_factors: '6x4x2x1'
        smoothing_factors: '4x2x1x0'
    deform:
        shrink_factors: '12x6x4x2x1'  # default in antsMVTC2: 6x4x2x1
        smoothing_factors: '6x3x2x1x0vox' # default in antsMVTC2: 3x2x1x0
        reg_iterations: '100x100x70x50x10' # default in antsMVTC2: 100x100x70x20
        transform_model: 'SyN[0.1,3,0]'
        sim_metric: CC
    shape_update:
        gradient_step: 0.25

