#
#--- filepaths
#

#laptop
#bids_dir: /media/greydon/Snobeanery1/PhD_data/retro_seeg/derivatives/scenes
bids_dir: /home/greydon/Documents/data/SEEG

#work computer
#bids_dir: /media/data/data/SEEG

#external drive
#bids_dir: /media/greydon/Snobeanery/PhD_data/hippunfold2

subject_prefix: P

#
#--- imaging volumes
#

contrast_t1:
    present: True

noncontrast_t1:
    present: True
    acq: False
    algo: greedy

post_ct:
    present: False
    position: 0
    algo: greedy

pet:
    present: True
    position: 0
    task: rest
    algo: greedy

seeg_contacts:
    present: False

#
#--- registration paramters
#

linear_reg:
    reg_aladin:
        dof: "-rigOnly" # use "-rigOnly" for 6 DOF and "" for 12 DOF
    greedy:
        n_iterations_affine: 100x50x0
        dof: 6

atlas_reg:
    reg_aladin:
        active: True
        dof: "" # use "-rigOnly" for 6 DOF and "" for 12 DOF
    greedy:
        active: False
        n_iterations_affine: 100x50x0
        n_iterations_deform: 100x40x20
        grad_sigma: 4.0vox
        warp_sigma: 1.4vox

#
#--- segmentation
#

default_k_tissue_classes: 3 #higher than 3 to capture contrast-enhanced regions too
atropos_smoothing_factor: '[0.2,1x1x1]'
convergence: '[3,0]'

#use this to specify custom values for subjects, e.g. here sub-P001 will have k=4 tissue classes for Atropos initialization
subject_k_tissue_classes: 
    081: 4
#    012: 4
#    039: 4
#    047: 4
#    050: 4
#    058: 4
#    061: 3

tissue_labels:
    - GM
    - WM
    - CSF

#
#--- connected piplines
#

fastsurfer:
    run: True
    home: "/home/greydon/Documents/GitHub/FastSurfer"
    py: "python"
    sid: 'fastsurfer'
    batch: 8
    threads: 4
    order: 0    #(0=nearest,1=linear(default),2=quadratic,3=cubic)
    seg_only: True
    vol_segstats: True

fmriprep:
    run: False
    fmriprep_license: resources/license.txt
    bids_filter: resources/bids_filter.json

hippunfold:
    run: False
    modality: T1w
    atlas_labels_tsv: resources/desc-subfields_atlas-bigbrain_dseg.tsv
    path_T1w: _ses-pre_run-01_T1w.nii.gz

subject_elec_ct: /bids/sub-f'{config['subject_prefix']}'{subject}/ses-post/ct/sub-f'{config['subject_prefix']}'{subject}_ses-post_acq-Electrode_run-01_ct.nii.gz
subject_elec_t1w: /bids/sub-f'{config['subject_prefix']}'{subject}/ses-post/anat/sub-f'{config['subject_prefix']}'{subject}_ses-post_acq-Electrode3D_run-01_T1w.nii.gz

#use this if a particular subject has a custom path
subject_elec_ct_custom: []
    #'047': /bids/sub-P{subject}/ses-post/ct/sub-P{subject}_ses-post_acq-Electrode_run-03_ct.nii.gz

subject_elec_t1w_custom: []

subject_seega_scene: /derivatives/seega_scenes/sub-P{subject}/SEEGA.fcsv
subject_electrodes: /derivatives/seega_coordinates/sub-P{subject}/sub-P{subject}_space-native_SEEGA.fcsv

#use this if a particular subject has custom path
subject_electrodes_custom: []

#
#--- template space/atlases
#

deface: False
facemask: resources/facemask.nii.gz
mean_reg2mean: resources/mean_reg2mean.nii.gz
generic_colors: resources/generic_colors.txt

adult_template:
    name: 'adult_template'
    space: 'MNI152NLin2009cSym'
    t1w: resources/tpl-MNI152NLin2009cSym/tpl-MNI152NLin2009cSym_res-1_T1w.nii.gz
    mask: resources/tpl-MNI152NLin2009cSym/tpl-MNI152NLin2009cSym_res-1_desc-brain_mask.nii.gz
    tissue_probseg: resources/tpl-MNI152NLin2009cSym/tpl-MNI152NLin2009cSym_res-1_label-{tissue}_probseg.nii.gz
    atlas_dseg_nii: resources/tpl-MNI152NLin2009cSym/tpl-MNI152NLin2009cSym_res-1_atlas-{atlas}_dseg.nii.gz
    atlas_dseg_tsv: resources/tpl-MNI152NLin2009cSym/tpl-MNI152NLin2009cSym_atlas-{atlas}_dseg.tsv

MNIPediatricAsymCohort2:
    name: 'MNIPediatricAsymCohort2'
    space: 'MNIPediatricAsymCohort2'
    t1w: resources/tpl-MNIPediatricAsym_from-4.5_to-8.5/tpl-MNIPediatricAsym_from-4.5_to-8.5_T1w.nii.gz
    mask: resources/tpl-MNIPediatricAsym_from-4.5_to-8.5/tpl-MNIPediatricAsym_from-4.5_to-8.5_desc-brain_mask.nii.gz
    tissue_probseg: resources/tpl-MNIPediatricAsym_from-4.5_to-8.5/tpl-MNIPediatricAsym_from-4.5_to-8.5_label-{tissue}_probseg.nii.gz
    atlas_dseg_nii: resources/tpl-MNI152NLin2009cSym/tpl-MNI152NLin2009cSym_res-1_atlas-{atlas}_dseg.nii.gz
    atlas_dseg_tsv: resources/tpl-MNI152NLin2009cSym/tpl-MNI152NLin2009cSym_atlas-{atlas}_dseg.tsv

MNIPediatricAsymCohort4:
    name: 'MNIPediatricAsymCohort4'
    space: 'MNIPediatricAsymCohort4'
    t1w: resources/tpl-MNIPediatricAsym_from-7.5_to-13.5/tpl-MNIPediatricAsym_from-7.5_to-13.5_T1w.nii.gz
    mask: resources/tpl-MNIPediatricAsym_from-7.5_to-13.5/tpl-MNIPediatricAsym_from-7.5_to-13.5_desc-brain_mask.nii.gz
    tissue_probseg: resources/tpl-MNIPediatricAsym_from-7.5_to-13.5/tpl-MNIPediatricAsym_from-7.5_to-13.5_label-{tissue}_probseg.nii.gz
    atlas_dseg_nii: resources/tpl-MNI152NLin2009cSym/tpl-MNI152NLin2009cSym_res-1_atlas-{atlas}_dseg.nii.gz
    atlas_dseg_tsv: resources/tpl-MNI152NLin2009cSym/tpl-MNI152NLin2009cSym_atlas-{atlas}_dseg.tsv

MNIPediatricAsymCohort6:
    name: 'MNIPediatricAsymCohort6'
    space: 'MNIPediatricAsymCohort6'
    t1w: resources/tpl-MNIPediatricAsym_from-13.0_to-18.5/tpl-MNIPediatricAsym_from-13.0_to-18.5_T1w.nii.gz
    mask: resources/tpl-MNIPediatricAsym_from-13.0_to-18.5/tpl-MNIPediatricAsym_from-13.0_to-18.5_desc-brain_mask.nii.gz
    tissue_probseg: resources/tpl-MNIPediatricAsym_from-13.0_to-18.5/tpl-MNIPediatricAsym_from-13.0_to-18.5_label-{tissue}_probseg.nii.gz
    atlas_dseg_nii: resources/tpl-MNI152NLin2009cSym/tpl-MNI152NLin2009cSym_res-1_atlas-{atlas}_dseg.nii.gz
    atlas_dseg_tsv: resources/tpl-MNI152NLin2009cSym/tpl-MNI152NLin2009cSym_atlas-{atlas}_dseg.tsv

atlases:
    - CerebrA

#number of times to dilate  (each time 3x3x3 mode dilation)
n_atlas_dilate: 3
n_init_mask_dilate: 1 


#parameters for ants transformation
ants:
    dim: 3
    intensity_opts: '-u 1 -w [0.01,0.99] -z 1'
    linear:
        reg_iterations: '1000x500x250x0'
        shrink_factors: '6x4x2x1'
        smoothing_factors: '4x2x1x0'
    deform:
        shrink_factors: '12x6x4x2x1'  # default in antsMVTC2: 6x4x2x1
        smoothing_factors: '6x3x2x1x0vox' # default in antsMVTC2: 3x2x1x0
        reg_iterations: '100x100x70x50x10' # default in antsMVTC2: 100x100x70x20
        transform_model: 'SyN[0.1,3,0]'
        sim_metric: CC
    shape_update:
        gradient_step: 0.25

singularity:
    neuroglia-core: "docker://khanlab/neuroglia-core:latest"
    fastsurfer: "docker://deepmi/fastsurfer:latest"
    freesurfer: "docker://freesurfer/freesurfer:latest"
    fmriprep: resources/fmriprep-21.0.0.simg
    neuroglia: docker://khanlab/neuroglia-core:latest
    hippunfold: docker://khanlab/hippunfold:latest
