#
#--- filepaths
#

#laptop
bids_dir: /home/greydon/Documents/data/clinical

#work computer
#bids_dir: /media/data/data/clinical

#external drive
#bids_dir: /media/veracrypt6/projects/stealthMRI


subject_prefix: P
deface: False
facemask: resources/facemask.nii.gz
mean_reg2mean: resources/mean_reg2mean.nii.gz

#
#--- imaging volumes
#

noncontrast_t1:
    present: False
    acq: T1map

contrast_t1:
    present: True

post_ct:
    present: False
    position: -1

seeg_contacts:
    present: False

pet:
    present: False
    position: -1
    task: rest

subject_t1w: /bids/sub-f'{config['subject_prefix']}'{subject}/ses-pre/anat/sub-f'{config['subject_prefix']}'{subject}_ses-pre_acq-FSPGR_run-01_T1w.nii.gz

#use this if a particular subject has a custom path
subject_t1w_custom: []

#
#--- segmentation
#

subject_elec_ct: /bids/sub-f'{config['subject_prefix']}'{subject}/ses-post/ct/sub-f'{config['subject_prefix']}'{subject}_ses-post_acq-Electrode_run-01_ct.nii.gz
subject_elec_t1w: /bids/sub-f'{config['subject_prefix']}'{subject}/ses-post/anat/sub-f'{config['subject_prefix']}'{subject}_ses-post_acq-Electrode3D_run-01_T1w.nii.gz

#use this if a particular subject has a custom path
subject_elec_ct_custom: []
    #'047': /bids/sub-P{subject}/ses-post/ct/sub-P{subject}_ses-post_acq-Electrode_run-03_ct.nii.gz

subject_elec_t1w_custom: []

subject_electrodes: /derivatives/seega_coordinates/sub-P{subject}/sub-P{subject}_space-native_SEEGA.fcsv

#use this if a particular subject has custom path
subject_electrodes_custom: []
template: MNI152NLin2009cSym

template_t1w: resources/tpl-{template}/tpl-{template}_res-1_T1w.nii.gz
template_mask: resources/tpl-{template}/tpl-{template}_res-1_desc-brain_mask.nii.gz 

template_atlas_dseg_nii: resources/tpl-{template}/tpl-{template}_res-1_atlas-{atlas}_dseg.nii.gz
template_atlas_dseg_tsv: resources/tpl-{template}/tpl-{template}_atlas-{atlas}_dseg.tsv

template_tissue_probseg: resources/tpl-{template}/tpl-{template}_res-1_label-{tissue}_probseg.nii.gz

tissue_labels:
    - GM
    - WM
    - CSF

atlases:
    - CerebrA

#number of times to dilate  (each time 3x3x3 mode dilation)
n_atlas_dilate: 3
n_init_mask_dilate: 1 

default_k_tissue_classes: 3 #higher than 3 to capture contrast-enhanced regions too
atropos_smoothing_factor: '[0.2,1x1x1]'
convergence: '[3,0]'

#use this to specify custom values for subjects, e.g. here sub-P001 will have k=4 tissue classes for Atropos initialization
subject_k_tissue_classes: []
#    001: 4
#    012: 4
#    039: 4
#    047: 4
#    050: 4
#    058: 4
#    061: 3


#parameters for ants transformation
ants:
    dim: 3
#    random_seed: 42 #requires ants version at least 2.3.1 (includes --random-seed option) - removed this for compatibility with older version of ANTS..  (e.g. that used in neuroglia-core)
    intensity_opts: '-u 1 -w [0.01,0.99] -z 1'
    linear:
        reg_iterations: '1000x500x250x0'
        shrink_factors: '6x4x2x1'
        smoothing_factors: '4x2x1x0'
    deform:
        shrink_factors: '12x6x4x2x1'  # default in antsMVTC2: 6x4x2x1
        smoothing_factors: '6x3x2x1x0vox' # default in antsMVTC2: 3x2x1x0
        reg_iterations: '100x100x70x50x10' # default in antsMVTC2: 100x100x70x20
        transform_model: 'SyN[0.1,3,0]'
        sim_metric: CC
    shape_update:
        gradient_step: 0.25

fastsurfer:
    run: False
    home: "/home/greydon/Documents/GitHub/FastSurfer"
    py: "python3"
    sid: 'fastsurfer'
    batch: 8
    threads: 4
    order: 0    #(0=nearest,1=linear(default),2=quadratic,3=cubic)
    seg_only: True
    vol_segstats: True

fmriprep:
    run: False
    fmriprep_license: resources/license.txt
    bids_filter: resources/bids_filter.json

singularity:
    neuroglia-core: "docker://khanlab/neuroglia-core:latest"
    fastsurfer: "docker://deepmi/fastsurfer:latest"
    freesurfer: "docker://freesurfer/freesurfer:latest"
    fmriprep: resources/fmriprep-21.0.0.simg
    neuroglia: docker://khanlab/neuroglia-core:latest
